global:
  scrape_interval:     15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "redis"
    scrape_interval: 5s
    static_configs:
    - targets: ["redis:6379"]

  - job_name: "exam_app"
    scrape_interval: 5s
    static_configs:
    - targets: ["app:5001"]
  #     labels:
  #       group: 'metrics'
  # - job_name: "app"
  #   dns_sd_configs:
  #     - names: ["app"]
  #       port: 5001
  #       type: A
  #       refresh_interval: 5s

